"""Add_doc_hash_column_to_document

Revision ID: 2c831af36926
Revises: 8284c5dd9502
Create Date: 2025-01-22 21:51:06.515978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c831af36926'
down_revision = '8284c5dd9502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_document_doc_hash'), 'document', ['doc_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_doc_hash'), table_name='document')
    op.drop_column('document', 'doc_hash')
    # ### end Alembic commands ###
