"""Create documents table with foreign key to users

Revision ID: 7c1250f1fdb2
Revises: f06be823367d
Create Date: 2024-12-05 21:41:58.933653-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1250f1fdb2'
down_revision = 'f06be823367d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('file_weight', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_description'), 'document', ['description'], unique=False)
    op.create_index(op.f('ix_document_document_type'), 'document', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_file_weight'), 'document', ['file_weight'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_pages'), 'document', ['pages'], unique=False)
    op.create_index(op.f('ix_document_s3_url'), 'document', ['s3_url'], unique=False)
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_index(op.f('ix_document_s3_url'), table_name='document')
    op.drop_index(op.f('ix_document_pages'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_file_weight'), table_name='document')
    op.drop_index(op.f('ix_document_document_type'), table_name='document')
    op.drop_index(op.f('ix_document_description'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
