"""modify Tags name to be unique

Revision ID: 8d976d43a9d7
Revises: d2381b16c65a
Create Date: 2024-12-17 18:33:08.652870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d976d43a9d7'
down_revision = 'd2381b16c65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_name', table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    # ### end Alembic commands ###
