"""Add is_uploaded_column to Document

Revision ID: 1aed4bf9d839
Revises: acc22207a8b8
Create Date: 2025-01-22 22:46:05.335737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aed4bf9d839'
down_revision: Union[str, None] = 'acc22207a8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_uploaded', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_uploaded')
    # ### end Alembic commands ###
