"""Add local_update_column to Document

Revision ID: 4b417a043374
Revises: 1aed4bf9d839
Create Date: 2025-01-23 13:56:36.239804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b417a043374'
down_revision: Union[str, None] = '1aed4bf9d839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('local_update', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'local_update')
    # ### end Alembic commands ###
