"""Add doc_hash_column_to_document

Revision ID: acc22207a8b8
Revises: c5d6d77e4666
Create Date: 2025-01-22 18:42:03.462435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc22207a8b8'
down_revision: Union[str, None] = 'c5d6d77e4666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_hash', sa.String(), nullable=True))
    op.drop_index('ix_documents_doc_id', table_name='documents')
    op.create_index(op.f('ix_documents_doc_hash'), 'documents', ['doc_hash'], unique=True)
    op.drop_column('documents', 'doc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_id', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_documents_doc_hash'), table_name='documents')
    op.create_index('ix_documents_doc_id', 'documents', ['doc_id'], unique=False)
    op.drop_column('documents', 'doc_hash')
    # ### end Alembic commands ###
