"""Add markdown_path column to Document

Revision ID: c5d6d77e4666
Revises: 947c9a36e72e
Create Date: 2025-01-22 14:00:15.819706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d6d77e4666'
down_revision: Union[str, None] = '947c9a36e72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('markdown_path', sa.String(), nullable=True))
    op.drop_column('documents', 'html_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('html_path', sa.VARCHAR(), nullable=True))
    op.drop_column('documents', 'markdown_path')
    # ### end Alembic commands ###
